site_name: PowerLumber
repo_url: https://github.com/jpsider/PowerLumber
theme: readthedocs
pages:
- Home: index.md
- PowerLumber Basics:
  - What is PowerLumber: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
